# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.3

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip git curl libzip-dev zlib1g-dev libmcrypt-dev default-mysql-client
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - pecl install mcrypt-1.0.2
          - docker-php-ext-enable mcrypt
          - docker-php-ext-install pdo_mysql
          - docker-php-ext-install zip
          - docker-php-ext-enable zip
          - composer install
          - ln -f -s .env.pipelines .env
          - ln -f -s .env.pipelines .env.testing
          - php artisan migrate
          - php artisan db:seed
          - php artisan serve &
          - sleep 5
          - vendor/bin/codecept build
          - vendor/bin/codecept run
          - curl -vk http://localhost:8000
        services:
          - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'
